version: "3.7"

services:
  database:
    image: postgres
    volumes:
      - ./back-end/tmp/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  back-end:
    build:
      context: ./back-end
    ports:
      - 3001:3001
    volumes:
      - ./back-end:/app
    depends_on:
      - database
    environment:
      DATABASE_HOST: database

  front-end:
    build:
      context: ./front-end
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
      - /app/node_modules/
    links:
      - back-end
    depends_on:
      - back-end
